const BANDS=['2m','70cm','1.25m','6m','10m','33cm','23cm','Other'];
const BAND_COVERAGE={'10m':40,'6m':35,'2m':25,'1.25m':20,'70cm':18,'33cm':12,'23cm':8};
const defaultPosition={lat:41.0998,lng:-81.736};
const state={position:defaultPosition,hasGPS:false,watchId:null,bands:new Set(JSON.parse(localStorage.getItem('bands')||'["2m","70cm"]')),range:+(localStorage.getItem('range')||50),ringOpacity:Math.min(.20,+(localStorage.getItem('ringOpacity')||.04)),outlineOpacity:Math.min(1,+(localStorage.getItem('outlineOpacity')||.25)),repeaters:[]};
const map=L.map('map',{zoomControl:true}).setView([defaultPosition.lat,defaultPosition.lng],9);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const markers=L.layerGroup().addTo(map); let userMarker;let popupOpen=false;
const $=s=>document.querySelector(s);

function bandFor(f){f=+f;if(f>=50&&f<54)return'6m';if(f>=28&&f<30)return'10m';if(f>=144&&f<148)return'2m';if(f>=219&&f<225)return'1.25m';if(f>=420&&f<450)return'70cm';if(f>=902&&f<928)return'33cm';if(f>=1240&&f<1300)return'23cm';return'Other'}
function miles(a,b){const r=3958.8,p=Math.PI/180,dlat=(b.lat-a.lat)*p,dlon=(b.lng-a.lng)*p;const x=Math.sin(dlat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dlon/2)**2;return 2*r*Math.asin(Math.sqrt(x))}
function bearing(a,b){const p=Math.PI/180,y=Math.sin((b.lng-a.lng)*p)*Math.cos(b.lat*p),x=Math.cos(a.lat*p)*Math.sin(b.lat*p)-Math.sin(a.lat*p)*Math.cos(b.lat*p)*Math.cos((b.lng-a.lng)*p);return(Math.atan2(y,x)/p+360)%360}
function reach(d){return d<=25?['Likely','likely']:d<=50?['Marginal','marginal']:['Long shot','unlikely']}
function clean(r){const frequency=+(r.frequency||r.freq||r.output||r.freq_mhz);const input=+(r.input_freq||r.input||0);const derivedOffset=input&&frequency?input-frequency:0;const offsetValue=r.offset??r.offset_mhz??derivedOffset;const mode=r.mode||(String(r.dmr).toLowerCase()==='yes'?'DMR':String(r.mixed_mode).toLowerCase()==='yes'?'FM / Mixed':'Not listed');return{callsign:String(r.callsign||r.call||'UNKNOWN'),frequency,offset:formatOffset(offsetValue,derivedOffset),tone:String(r.tone||r.pl_tone||r.pl||r.ctcss||''),mode:String(mode),location:String(r.location||r.city||''),state:String(r.state||''),lat:coordinate(r.lat??r.latitude,-90,90),lng:coordinate(r.lng??r.lon??r.longitude,-180,180),county:String(r.county||''),downlinkTone:String(r.downlinkTone||r.downlinktone||r.downlink_tone||''),digitalAccess:String(r.digitalAccess||r.digitalaccess||r.digital_access||''),approximate:!!r.approximate,band:r.band||bandFor(frequency),coverageMiles:+(r.coverageMiles||r.coverage_miles||r.coverage||0),notes:String(r.notes||'')}}
function formatOffset(value,derived){if((value==='+'||value==='-')&&derived)return `${derived>0?'+':''}${derived.toFixed(3)}`;if(value===undefined||value===null||value==='')return'';let n=+value;if(!Number.isFinite(n))return String(value);if(derived&&Math.sign(n)!==Math.sign(derived))n=Math.abs(n)*Math.sign(derived);if(!derived&&n>0)n=Math.abs(n);return`${n>0?'+':''}${n.toFixed(3)}`}
function coordinate(v,min,max){if(v===undefined||v===null||String(v).trim()==='')return null;const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max?n:null}
function located(r){return Number.isFinite(r.lat)&&Number.isFinite(r.lng)}
function valid(r){return Number.isFinite(r.frequency)&&r.frequency>0&&r.frequency<=10000}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

function coverageFor(r){return r.coverageMiles>0?r.coverageMiles:(BAND_COVERAGE[r.band]||15)}
function applyRingOpacity(){markers.eachLayer(layer=>{if(layer instanceof L.Circle&&layer.options.color!=='#ff7a1a')layer.setStyle({fillOpacity:state.ringOpacity,opacity:state.outlineOpacity})})}

function renderBands(){const box=$('#bands');box.innerHTML='';BANDS.forEach(b=>{const x=document.createElement('button');x.className='chip '+(state.bands.has(b)?'active':'');x.textContent=b;x.onclick=()=>{state.bands.has(b)?state.bands.delete(b):state.bands.add(b);save();renderBands();render()};box.append(x)})}
function save(){localStorage.setItem('bands',JSON.stringify([...state.bands]));localStorage.setItem('range',state.range);localStorage.setItem('ringOpacity',state.ringOpacity);localStorage.setItem('outlineOpacity',state.outlineOpacity)}
function setMapLocked(locked,recenter=true){$('#follow').checked=locked;localStorage.setItem('mapLocked',String(locked));$('#followLabel').textContent=locked?'🔒 Map locked to GPS':'🔓 Map unlocked — free pan';const mobile=$('#mobileMapLock');mobile.classList.toggle('active',locked);mobile.setAttribute('aria-pressed',String(locked));mobile.firstChild.textContent=locked?'🔒':'🔓';mobile.querySelector('span').textContent=locked?'Locked':'Unlocked';if(locked&&recenter&&state.hasGPS){setView('map');map.setView([state.position.lat,state.position.lng],Math.max(map.getZoom(),11))}if(recenter)toast(locked?'Map locked — following your location':'Map unlocked — pan and zoom freely')}
function updateDatasetStatus(){const el=$('#datasetStatus'),meta=JSON.parse(localStorage.getItem('datasetMeta')||'null');el.classList.remove('stale');if(!meta){el.textContent=`Upload a CSV · ${state.repeaters.length} records`;return}const imported=new Date(meta.importedAt),days=Math.max(0,Math.floor((Date.now()-imported.getTime())/86400000));const age=days===0?'today':`${days} day${days===1?'':'s'} ago`;el.textContent=`${meta.fileName} · ${meta.recordCount} records · imported ${age}`;if(days>60){el.classList.add('stale');el.textContent+=' · update recommended'}}
function popup(r,d,b,quality){return `<div class="popup-title">${esc(r.callsign)} · ${r.frequency.toFixed(3)}</div><b>${esc(r.band)} · ${esc(r.mode)}</b><br>${esc(r.offset||'Offset not listed')}${r.tone?` · TX tone ${esc(r.tone)}`:''}<br>${d.toFixed(1)} mi · bearing ${Math.round(b)}°<br>${esc(r.location)}${r.state?', '+esc(r.state):''}<br>${r.approximate?'Approximate town location; not the repeater site.':`Estimated radius: ${coverageFor(r)} mi (not guaranteed)`}<br><b>${esc(quality)}</b>`}
function updateImportNotice(){const unplaced=state.repeaters.filter(r=>!located(r)).length;$('#importNotice').textContent=unplaced?`${state.repeaters.length} repeaters imported; ${unplaced} have no coordinates. They are listed below. Choose “Place town on map” to add an approximate location, or import a CSV with latitude and longitude for exact pins.`:state.repeaters.length?`${state.repeaters.length} repeaters loaded. CSV imports are saved in this browser only.`:'Upload your repeater CSV. Imports are saved in this browser only.';}
function persistDataset(){localStorage.setItem('repeaterData',JSON.stringify(state.repeaters));updateImportNotice();render();}
let placing=null;
function placeTown(r){placing=r;setView('map');$('#importNotice').textContent=`Click the map at the town center for ${r.location}, ${r.state}. The point will be used for repeaters in this same town / county. These will be marked approximate. Press Escape to cancel.`;}
map.on('click',e=>{if(!placing)return;const r=placing;placing=null;state.repeaters.forEach(x=>{if(x.location===r.location&&x.state===r.state&&x.county===r.county&&!located(x)){x.lat=e.latlng.lat;x.lng=e.latlng.lng;x.approximate=true;}});persistDataset();toast('Approximate town location saved');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&placing){placing=null;updateImportNotice()}});
function render(){if(popupOpen)return;markers.clearLayers();const query=($('#repeaterSearch')?.value||'').trim().toLowerCase();const rows=state.repeaters.map(r=>({...r,d:located(r)?miles(state.position,r):null,b:located(r)?bearing(state.position,r):null})).filter(r=>state.bands.has(r.band)&&(r.d===null||r.d<=state.range)&&(!query||[r.callsign,r.frequency.toFixed(3),r.location,r.state,r.mode].some(v=>String(v).toLowerCase().includes(query)))).sort((a,b)=>(a.d??Infinity)-(b.d??Infinity));$('#count').textContent=`${rows.length} matching · ${rows.filter(r=>r.d!==null).length} mapped`;const list=$('#list');list.innerHTML='';rows.forEach(r=>{const [q,cls]=r.d===null?['No coordinates','unlocated']:r.approximate?['Town estimate','marginal']:reach(r.d);let marker;const color=cls==='likely'?'#22b878':cls==='marginal'?'#e5ad26':'#e14d63';if(r.d!==null){const coverage=r.approximate?null:L.circle([r.lat,r.lng],{radius:coverageFor(r)*1609.344,color,weight:1,opacity:state.outlineOpacity,fillColor:color,fillOpacity:state.ringOpacity,interactive:false}).addTo(markers);marker=L.circleMarker([r.lat,r.lng],{radius:r.approximate?7:9,color:r.approximate?'#ffd166':'#fff',weight:2,fillColor:color,fillOpacity:.9}).bindPopup(popup(r,r.d,r.b,q)).on('popupopen',()=>{popupOpen=true;if(coverage)coverage.setStyle({color:'#ff7a1a',weight:3,opacity:1,fillColor:'#ff7a1a',fillOpacity:.25})}).on('popupclose',()=>{popupOpen=false;if(coverage)coverage.setStyle({color,weight:1,opacity:state.outlineOpacity,fillColor:color,fillOpacity:state.ringOpacity})}).addTo(markers);if(coverage)coverage.bringToBack();}
const card=document.createElement('article');card.className=`card ${cls}`;card.innerHTML=`<div class="card-top"><span class="call">${esc(r.callsign)}</span><span class="badge">${q}</span></div><div class="freq">${r.frequency.toFixed(3)} MHz</div><div class="details">${esc(r.band)} · ${esc(r.mode)} · ${esc(r.offset||'offset n/a')}${r.tone?' · TX tone '+esc(r.tone):''}${r.downlinkTone?' · RX tone '+esc(r.downlinkTone):''}</div><div class="where">${r.d===null?'Distance unavailable':(r.approximate?'~':'')+r.d.toFixed(1)+' mi · '+Math.round(r.b)+'°'} · ${esc(r.location)}${r.state?', '+esc(r.state):''}</div>`;
if(r.digitalAccess){const note=document.createElement('div');note.className='details';note.textContent='Digital access: '+r.digitalAccess;card.append(note)}
if(marker){card.tabIndex=0;const view=()=>{setView('map');map.setView([r.lat,r.lng],10);marker.openPopup()};card.onclick=view;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();view()}}}else{const btn=document.createElement('button');btn.textContent='Place town on map';btn.onclick=()=>placeTown(r);card.append(btn)}list.append(card)});if(!rows.length)list.innerHTML='<div class="details" style="padding:12px">No repeaters match. Change the search, range or bands, or upload a CSV.</div>';}
function updatePosition(p){state.position={lat:p.coords.latitude,lng:p.coords.longitude};state.hasGPS=true;$('#gpsStatus').textContent=`GPS accuracy ±${Math.round(p.coords.accuracy)} m`;if(!userMarker)userMarker=L.marker([state.position.lat,state.position.lng],{icon:L.divIcon({className:'',html:'<div class="user-dot"></div>',iconSize:[20,20],iconAnchor:[10,10]})}).addTo(map);else userMarker.setLatLng(state.position);if($('#follow').checked&&!popupOpen)map.setView([state.position.lat,state.position.lng],Math.max(map.getZoom(),10));if(!popupOpen)render()}
function locate(){if(!navigator.geolocation)return toast('Location is not supported by this browser.');if(state.watchId!==null){navigator.geolocation.clearWatch(state.watchId);state.watchId=null;$('#locate').textContent='◎ Use my location';$('#gpsStatus').textContent='GPS paused';return}$('#locate').textContent='■ Stop GPS';state.watchId=navigator.geolocation.watchPosition(updatePosition,e=>{toast(e.message);$('#gpsStatus').textContent='GPS unavailable — showing map center'},{enableHighAccuracy:true,maximumAge:5000,timeout:15000})}
function setFilters(open){document.body.classList.toggle('filters-open',open);$('#filterToggle').setAttribute('aria-expanded',String(open))}
function setView(mode){const list=mode==='list';document.body.classList.toggle('list-mode',list);$('#mapView').classList.toggle('active',!list);$('#listView').classList.toggle('active',list);$('#mapView').setAttribute('aria-pressed',String(!list));$('#listView').setAttribute('aria-pressed',String(list));if(!list)setTimeout(()=>map.invalidateSize(),80)}
function searchRepeaters(term){render();const query=term.trim().toLowerCase(),box=$('#searchResults');$('.map-search').classList.toggle('has-value',!!query);box.innerHTML='';if(!query){box.classList.remove('open');return;}const found=state.repeaters.filter(r=>[r.callsign,r.frequency.toFixed(3),r.location,r.state,r.mode].some(v=>String(v).toLowerCase().includes(query))).slice(0,12);box.classList.add('open');if(!found.length){box.textContent='No matching repeaters.';return;}found.forEach(r=>{const b=document.createElement('button');b.className='search-result';b.setAttribute('role','option');b.textContent=`${r.callsign} · ${r.frequency.toFixed(3)} MHz · ${r.location}${located(r)?'':' · no coordinates'}`;b.onclick=()=>{box.classList.remove('open');if(located(r))selectRepeater(r);else setView('list')};box.append(b)});}
function selectRepeater(r){popupOpen=false;const d=miles(state.position,r);state.bands.add(r.band);if(d>state.range)state.range=Math.min(150,Math.ceil(d/5)*5);$('#range').value=state.range;$('#rangeLabel').textContent=state.range+' mi';save();renderBands();setView('map');render();map.setView([r.lat,r.lng],10);const ring=L.circle([r.lat,r.lng],{radius:r.approximate?0:coverageFor(r)*1609.344,color:'#ff7a1a',weight:3,opacity:1,fillColor:'#ff7a1a',fillOpacity:Math.max(.25,state.ringOpacity),interactive:false}).addTo(map);popupOpen=true;L.popup().setLatLng([r.lat,r.lng]).setContent(popup(r,d,bearing(state.position,r),reach(d)[0])).openOn(map);map.once('popupclose',()=>{popupOpen=false;map.removeLayer(ring);applyRingOpacity()});$('#searchResults').classList.remove('open')}
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function parseCSV(text){
  const rows=[];let row=[],field='',quoted=false;
  text=text.replace(/^\uFEFF/,'');
  for(let i=0;i<text.length;i++){
    const ch=text[i];
    if(ch==='"'){
      if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted;
    }else if(ch===','&&!quoted){row.push(field);field=''}
    else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(v=>v.trim()))rows.push(row);row=[];field=''}
    else field+=ch;
  }
  if(quoted)throw new Error('CSV has an unclosed quote');
  row.push(field);if(row.some(v=>v.trim()))rows.push(row);
  if(rows.length<2)throw new Error('CSV needs a header and at least one repeater');
  const aliases={inputfrequencymhz:'input_freq',offsetmhz:'offset',outputfreq:'frequency',inputfreq:'input_freq',uplinktone:'tone',downlinktone:'downlinktone',modes:'mode',digitalaccess:'digitalaccess',call:'callsign',repeatercallsign:'callsign',freqmhz:'frequency',frequencymhz:'frequency',outputfrequency:'frequency',frequencyoutput:'frequency',rxfrequency:'frequency',inputfrequency:'input_freq',txfrequency:'input_freq',pl:'tone',pltone:'tone',ploutput:'tone',outputtone:'tone',ctcss:'tone',city:'location',nearestcity:'location',latitude:'lat',longitude:'lng',long:'lng',lon:'lng',stateprovince:'state'};
  const heads=rows.shift().map(h=>{const key=h.trim().toLowerCase().replace(/[^a-z0-9]/g,'');return aliases[key]||key});
  if(!heads.includes('frequency')&&!heads.includes('freq'))throw new Error('CSV needs an Output Freq or frequency column');
  return rows.map(values=>Object.fromEntries(heads.map((h,i)=>[h,(values[i]||'').trim()])));
}
function mergedRecords(raw){const groups=new Map();for(const row of raw){const n=clean(row);if(!valid(n))continue;const key=n.callsign.toUpperCase()+'|'+n.frequency.toFixed(6),source=row.__source??(located(n)?'coordinates':'radio');const bucket=groups.get(key)||[];const candidates=bucket.filter(e=>!e.sources.has(source));let target;if(candidates.length===1)target=candidates[0];else if(candidates.length>1){const ranked=candidates.map(e=>{const old=clean(e.raw);return {e,score:(old.location.toUpperCase()===n.location.toUpperCase()?4:0)+(old.tone&&old.tone===n.tone?3:0)}}).sort((a,b)=>b.score-a.score);if(ranked[0].score>0&&ranked[0].score>(ranked[1]?.score??-1))target=ranked[0].e;}if(!target){target={raw:{},sources:new Set()};bucket.push(target);}for(const [k,v] of Object.entries(row)){if(v!==undefined&&v!==null&&String(v).trim()!=='')target.raw[k]=v;}target.sources.add(source);groups.set(key,bucket);}return [...groups.values()].flat().map(e=>clean(e.raw)).filter(valid)}
async function importFiles(files){try{let raw=[];let sourceIndex=0;for(const file of files){if(file.size>10000000)throw new Error('Each file must be under 10 MB');const text=await file.text(),data=file.name.toLowerCase().endsWith('.json')?JSON.parse(text):parseCSV(text);const arr=Array.isArray(data)?data:(data.records||data.repeaters||[]);raw.push(...arr.map(r=>({...r,__source:sourceIndex})));sourceIndex++;}const cleaned=mergedRecords(raw);if(!cleaned.length)throw new Error('No valid repeaters found; check the output frequency column');const names=[...files].map(f=>f.name).join(' + ');localStorage.setItem('repeaterData',JSON.stringify(cleaned));localStorage.setItem('datasetMeta',JSON.stringify({fileName:names,recordCount:cleaned.length,importedAt:new Date().toISOString()}));state.repeaters=cleaned;popupOpen=false;map.closePopup();render();updateDatasetStatus();updateImportNotice();if(cleaned.every(r=>!located(r)))setView('list');toast(`Imported ${cleaned.length} repeaters`);}catch(e){$('#importNotice').textContent=`Import failed: ${e.message}. Your previous dataset was kept.`;toast(`Import failed: ${e.message}`);}finally{$('#fileInput').value='';}}
$('#range').value=state.range;$('#rangeLabel').textContent=state.range+' mi';$('#range').oninput=e=>{state.range=+e.target.value;$('#rangeLabel').textContent=state.range+' mi';save();render()};$('#locate').onclick=locate;$('#allBands').onclick=()=>{state.bands=new Set(BANDS);save();renderBands();render()};$('#clearBands').onclick=()=>{state.bands.clear();save();renderBands();render()};$('#quickImport').onclick=()=>$('#fileInput').click();$('#importButton').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>e.target.files.length&&importFiles(e.target.files);$('#filterToggle').onclick=()=>setFilters(true);$('#closeFilters').onclick=()=>setFilters(false);$('#filterShade').onclick=()=>setFilters(false);$('#mapView').onclick=()=>setView('map');$('#listView').onclick=()=>setView('list');$('#follow').onchange=e=>setMapLocked(e.target.checked);$('#mobileMapLock').onclick=()=>setMapLocked(!$('#follow').checked);$('#mobileLocate').onclick=()=>{setView('map');setMapLocked(true,false);if(state.watchId===null)locate();else if(state.hasGPS)map.setView([state.position.lat,state.position.lng],Math.max(map.getZoom(),11))};map.on('moveend',()=>{if(!state.hasGPS&&!$('#follow').checked){const c=map.getCenter();state.position={lat:c.lat,lng:c.lng};render()}});
fetch('repeaters.json').then(r=>r.json()).then(data=>{const saved=localStorage.getItem('repeaterData');state.repeaters=(saved?JSON.parse(saved):data).map(clean).filter(valid);render();updateDatasetStatus();updateImportNotice()}).catch(()=>{state.repeaters=[];render();updateDatasetStatus();updateImportNotice()});renderBands();setMapLocked(localStorage.getItem('mapLocked')!=='false',false);
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
$('#coverageOpacity').value=Math.round(state.ringOpacity*100);$('#opacityLabel').textContent=Math.round(state.ringOpacity*100)+'%';$('#coverageOpacity').oninput=e=>{state.ringOpacity=+e.target.value/100;$('#opacityLabel').textContent=e.target.value+'%';save();applyRingOpacity()};
$('#outlineOpacity').value=Math.round(state.outlineOpacity*100);$('#outlineLabel').textContent=Math.round(state.outlineOpacity*100)+'%';$('#outlineOpacity').oninput=e=>{state.outlineOpacity=+e.target.value/100;$('#outlineLabel').textContent=e.target.value+'%';save();applyRingOpacity()};
$('#repeaterSearch').oninput=e=>searchRepeaters(e.target.value);$('#repeaterSearch').onfocus=e=>searchRepeaters(e.target.value);$('#clearSearch').onclick=()=>{$('#repeaterSearch').value='';searchRepeaters('');$('#repeaterSearch').focus()};
map.on('layeradd',e=>{const layer=e.layer;if(layer instanceof L.Circle&&layer.options.interactive===false&&layer.options.color!=='#ff7a1a')layer.setStyle({fillOpacity:state.ringOpacity,opacity:state.outlineOpacity})});map.on('popupclose',()=>setTimeout(applyRingOpacity,0));
